### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by driesvints**

### CODE REVIEW

**Comment by freekmurze** [comment]
Feel free to remove Travis and use the GitHub Action template from one of our other packages.

**Comment by driesvints** [comment]
Github Actions still needs to be activated.

I've btw not added the caching step because these days Composer 2 is even faster than the cache. We noticed that when working on the Laravel repos.

**Comment by freekmurze** [comment]
Thanks, much appreciated.

**Comment by driesvints** [comment]
@freekmurze please note that Github Actions weren't running yet (see my comment above). They do seem to run on master where they are failing now. I'll check in on that.

**Pull request merged**
